</div>

<div class="gray-line" style="margin-top: 20px;margin-bottom: 20px"></div>

<div id="footer">
    <div style="float: left;">
        &copy;<?php echo date("Y"); echo ' '.SITE_NAME?> , Ltd.
    </div>
    <?php
    if (!isset($_SESSION["userBlocked"])) { ?>
    <div style="float: right;">
        <a href='<?= SITE_ROOT; ?>'>Home</a> |
        <a href='<?= SITE_ROOT; ?>terms'>Terms of Use</a> |
        <a href='<?= SITE_ROOT; ?>privacy'>Privacy Policy</a>
        <?php
        } ?>
    </div>
    <br/>
    <br/>
</div>

</div>
</body>
</html>
