<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">

<head>
    <?php require_once VIEW_DIR."templates/head.phtml"; ?>
</head>
<body>
<?php
$isMobile = false;
$modalHdl = new \App\Models\Base();
$modalHdl->createCustomModal('alert');
$modalHdl->createCustomModal('confirm');

//get the isMobile method from the Mobiledetect_model
if ($isMobile) { ?>
    <div class="mobile_header">
        <div style="margin-left:auto;margin-right:auto;width: 1200px;">
            <div style="width: 400px; float: left; padding-left: 30px; padding-top: 15px; font-size: 15px; font-family: Helvetica;">
            </div>
            <div style="width: 460px; float: right; padding-right: 14px; padding-top: 12px;">
            </div>
        </div>
    </div>
    <?php
}
?>

<div id="wrapper">
    <div id="header">
        <div style="float: left; height: 70px; width: 410px;">
            <a href="<?= SITE_ROOT; ?>"><img width="177px" height="96px" border="0" src="<?= IMAGES_URL; ?>logo.png"></a>
        </div>
        <div style="float: right; padding-right: 50px; padding-top: 30px;">
            <div style="float: right;">
                <br style="clear: left"/>
            </div>
        </div>
    </div>
    <div id="main">
