<title><?= SITE_NAME; ?></title>
<link rel="stylesheet" href="<?= CSS_URL; ?>style_code_igniter_2014.css" type="text/css"/>
<link rel="stylesheet" href="<?= CSS_URL; ?>header_style.css" type="text/css"/>
<link rel="stylesheet" type="text/css" media="all" href="<?= CSS_URL; ?>navigationBar.css"/>
<link rel="stylesheet" type="text/css" media="all" href="<?= CSS_URL; ?>cssStyleManagement.css">
<link rel="stylesheet" type="text/css" media="all" href="<?= JS_URL; ?>libraries/jqueryui/jquery-ui.min.css">
<link rel="stylesheet" type="text/css" media="all" href="<?= JS_URL; ?>libraries/jqueryui/jquery-ui.theme.min.css">
<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js"></script>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.2/font/bootstrap-icons.css">
<link rel="stylesheet" href="https://unpkg.com/bootstrap-table@1.22.1/dist/bootstrap-table.min.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.65.5/codemirror.min.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

<script type="text/javascript" src="<?= JS_URL; ?>header_links.js"></script>
<script type="text/javascript" src="<?= JS_URL; ?>navigationBar.js"></script>
<script type="text/javascript" src="<?= JS_URL; ?>globalSearch.js"></script>
<script type="text/javascript" src="<?= JS_URL; ?>jsStyleManagement.js"></script>
<script type="text/javascript" src="<?= JS_URL; ?>jsAssemblyManagement.js"></script>
<script type="text/javascript" src="<?= JS_URL; ?>libraries/jqueryui/jquery-ui.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
<script src="https://unpkg.com/bootstrap-table@1.22.1/dist/bootstrap-table.min.js"></script>

<script>
    let baseUrl = '<?php echo SITE_ROOT ?>';
</script>