import React, { Component } from "react"
import Table from 'react-bootstrap/Table'
import Button from 'react-bootstrap/Button'

import Skip from '../../Shared/Skip'

//import "../Create.css"

const title = "OAuth 2.0"
const p1 = "Our web services include Order Placement, Cancel Order and Redo Order Placement.  All these services require a valid Access Token. Access Tokens are generated by submitting a POST request with  user credentials to the URL given below."
const p2 = "Once a valid access token has been obtained, we recommend you store it in a safe place and begin using it for placing, cancelling, or resubmitting orders by sending it in the header as a bearer token shown below."
const p3 = "Example: "
const p4 = "Authorization: Bearer 9b238596775fe9956f655d24a23693abb10ad411"
const p5 = "Please note that access tokens will expire within one hour and that by submitting a new token request, previously generated tokens are immediately expired."

class Request extends Component {
    
    componentDidUpdate() {
        window.scrollTo(0, 0);
    }
    
    render() {        
        const skipButton = (this.props.skipped || this.props.approved) ? '' : (<Skip nextStage='redo' score={50}/>);
        var increasePercentage = this.props.asUser? 0 : 2 ;

         return ( 
            <div className="request pt-3">
                <h5><b>{title}</b></h5>
                <p>{p1}</p>
                
                {/*<hr className="my-4"/>*/}

                <h5><b>Where to Send Your Post Request</b></h5>
                <p className="request-url p-2">https://jondohd.com/jondoApi/generateToken.php</p>
                <br></br>

                <h5><b>Request Data</b></h5>
                <Table striped bordered hover>
                    <thead>
                        <tr>
                            <th>Name</th>
                            <th className = "width100" >Data Type</th>
                            <th>Value Description</th>
                            <th>Required?</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>userId</td>
                            <td>Number (5)</td>
                            <td>Your user account ID will be provided to you and must be passed with every request</td>
                            <td>Y</td>
                        </tr>
                        <tr>
                            <td>apiKey</td>
                            <td>String (30)</td>
                            <td>Your api key will be provided to you and must be passed with each request so that your identity can be validated</td>
                            <td>Y</td>
                        </tr>
                    </tbody>
                </Table>
                <br></br>
                
                <p>{p2}</p>
                <p>{p3}</p>
                <p>{p4}</p>
                <p>{p5}</p>
                <br></br>

                <h5><b>Response Data</b></h5>
                <Table striped bordered hover>
                    <thead>
                        <tr>
                            <th>Name</th>
                            <th className = "width100" >Data Type</th>
                            <th>Value Description</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>access_token</td>
                            <td>String (256)</td>
                            <td>Access Token string is used in header while submitting any request to the API</td>
                        </tr>
                        <tr>
                            <td>expires_in</td>
                            <td>Number (5)</td>
                            <td>Seconds value that represents the lifespan of the access token. Please note that expired token cannot be used for placing any requests.</td>
                        </tr>
                        <tr>
                            <td>token_type</td>
                            <td>String (32)</td>
                            <td>Bearer token type</td>
                        </tr>
                    </tbody>
                </Table>

                <div className="d-flex mt-5 mb-3 mt-auto" style={{justifyContent:"space-between"}}>
                    <Button
                        disabled
                        size="lg"
                        variant="outline-light"
                        onClick={() => this.props.handleNext('', 0) }
                    >
                    </Button>
                    <div style={{display:"inline-flex"}}>
                        <Button
                            size="lg"
                            variant="primary"
                            onClick={() => this.props.handleNext('sample_cancel', increasePercentage) }
                        >
                            NEXT
                        </Button>
                        {skipButton}
                    </div>
                </div>
             
            </div>
        );
    }
}


export default Request;
